drop table APAS.Batch_JOB_EXECUTION_CONTEXT;
drop table APAS.Batch_JOB_EXECUTION_PARAMS;
drop table APAS.Batch_JOB_EXECUTION_SEQ;
drop table APAS.Batch_JOB_SEQ;
drop table APAS.Batch_STEP_EXECUTION_CONTEXT;
drop table APAS.Batch_STEP_EXECUTION_SEQ;
drop table APAS.Batch_STEP_EXECUTION;
drop table APAS.Batch_JOB_EXECUTION;
drop table APAS.Batch_JOB_INSTANCE;